apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-abs-app
  labels:
    app: abs-app
spec:
  selector:
    app: abs-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
