apiVersion: apps/v1
kind: Deployment
metadata:
  name: abs-app
  labels:
    app: abs-app
spec:
  selector:
    matchLabels:
      app: abs-app
  template:
    metadata:
      labels:
        app: abs-app
    spec:
      containers:
      - name: abs-app
        image: shoeb151/abs-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
